# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aguara < Formula
  desc "Security scanner for AI agent skills and MCP servers"
  homepage "https://github.com/garagon/aguara"
  version "0.11.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/garagon/aguara/releases/download/v0.11.0/aguara_0.11.0_darwin_amd64.tar.gz"
      sha256 "7a3e2154bcf2c77d596d41a3d2c11a973d58b562223a3d51ad0bb7fe31b75991"

      define_method(:install) do
        bin.install "aguara"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/garagon/aguara/releases/download/v0.11.0/aguara_0.11.0_darwin_arm64.tar.gz"
      sha256 "1ca22a62a853f1fcfe7ec831ab5aa559c06325856979e8ae0bb66f046bce8f48"

      define_method(:install) do
        bin.install "aguara"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/garagon/aguara/releases/download/v0.11.0/aguara_0.11.0_linux_amd64.tar.gz"
      sha256 "4eaec8b341ab894c239ffccd6fb77eb86f0dad484cf26f2c81e833247848d517"
      define_method(:install) do
        bin.install "aguara"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/garagon/aguara/releases/download/v0.11.0/aguara_0.11.0_linux_arm64.tar.gz"
      sha256 "7d481a29e4e8cc965a9791912f44a48b389cb9c877933de262f8efed274e2846"
      define_method(:install) do
        bin.install "aguara"
      end
    end
  end

  test do
    system "#{bin}/aguara", "version"
  end
end
