# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aguara < Formula
  desc "Security scanner for AI agent skills and MCP servers"
  homepage "https://github.com/garagon/aguara"
  version "0.27.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/garagon/aguara/releases/download/v0.27.0/aguara_0.27.0_darwin_amd64.tar.gz"
      sha256 "42db53680e6ac77b14046dfe4b73e777dd88cb42aad7174937d740b1a88a4171"

      define_method(:install) do
        bin.install "aguara"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/garagon/aguara/releases/download/v0.27.0/aguara_0.27.0_darwin_arm64.tar.gz"
      sha256 "96f922d2ac3919cc2bfc565a46a29ac354862663286f1a1dd34596cfc14a7003"

      define_method(:install) do
        bin.install "aguara"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/garagon/aguara/releases/download/v0.27.0/aguara_0.27.0_linux_amd64.tar.gz"
      sha256 "612a6e7f264f117106ca08f49df3177870875b34e6150b3c500140b634b354b6"
      define_method(:install) do
        bin.install "aguara"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/garagon/aguara/releases/download/v0.27.0/aguara_0.27.0_linux_arm64.tar.gz"
      sha256 "01bab4084ff67a352229072d647bcfe59038ebc0bd7a5f3c5b1487e94c1c76b1"
      define_method(:install) do
        bin.install "aguara"
      end
    end
  end

  test do
    system "#{bin}/aguara", "version"
  end
end
