# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aguara < Formula
  desc "Security scanner for AI agent skills and MCP servers"
  homepage "https://github.com/garagon/aguara"
  version "0.21.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/garagon/aguara/releases/download/v0.21.0/aguara_0.21.0_darwin_amd64.tar.gz"
      sha256 "3fbc0236439be11c1586e6674076d7f76f900fa0d979a6dc11b3a47944f37f3a"

      define_method(:install) do
        bin.install "aguara"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/garagon/aguara/releases/download/v0.21.0/aguara_0.21.0_darwin_arm64.tar.gz"
      sha256 "f06f9919f22b601dd3fa6237a6a9c3c75e37214de4964d58671d0f7a7793f5c7"

      define_method(:install) do
        bin.install "aguara"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/garagon/aguara/releases/download/v0.21.0/aguara_0.21.0_linux_amd64.tar.gz"
      sha256 "d9b8577d1e48c8aa95f21f8e0b47f254a6d57733b1760a3dc39bbbd4bbef5e7e"
      define_method(:install) do
        bin.install "aguara"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/garagon/aguara/releases/download/v0.21.0/aguara_0.21.0_linux_arm64.tar.gz"
      sha256 "e79da99de001cceaed4540bd52a4423f2fd39c19d18e67f3de879392a0f699fc"
      define_method(:install) do
        bin.install "aguara"
      end
    end
  end

  test do
    system "#{bin}/aguara", "version"
  end
end
